### ISSUE TITLE
3.0 doesn't have Vue.extend anymore. 

### ISSUE THREAD

**Issue by HamptonNorth** [malekim/v-idle#18]
Get error `Uncaught TypeError: Vue.extend is not a function at v-idle.js:6`

I'm presuming this is a "Doesn't work with Vue3" issue. Is that the case?

If so, are there any plans to upgrade the code?

Many thanks

**Comment by malekim** [comment]
It's not vue3 ready. Currently I'm working on the vue3 version, it will be released on the next branch.

**Comment by HamptonNorth** [comment]
Thanks for reply. Out of interest have you looked at *IdleDetector* api for
Chrome?

Rob

**Comment by malekim** [comment]
I didn't yet, but looks promising!

**Comment by MoeBensu** [comment]
@malekim first of all, thanks for the work your pulling off here. I wanna ask, if you could give an update about the progress status of including vue 3 support?

**Comment by malekim** [comment]
@MoeNeuron 
Added vue3 support
