### ISSUE TITLE
Support for Vue 3

### ISSUE THREAD

**Issue by elselapatha** [malekim/v-idle#26]
Better if you can support for vue 3

**Comment by ux-engineer** [comment]
Upcoming?

**Comment by davidmitchell247** [comment]
Any update on this?

**Comment by cdanielzt** [comment]
Keep waiting for Vue 3 support

**Comment by eladcandroid** [comment]
@davidmitchell247 
@cdanielzt 
@ux-engineer 
@elselapatha 

Please check my repo
https://github.com/eladcandroid/v-idle-3

**Comment by malekim** [comment]
@elselapatha @ux-engineer @davidmitchell247 @cdanielzt
Added support for vue3
