### ISSUE TITLE
Event on-active

### ISSUE THREAD

**Issue by Kuro-dev** [malekim/v-idle#31]
I want to automatically log a user out if they are idle for too long. 
for that i want to show a small popup that lets them know in advance. 
Now i would also like to automatically dismiss this notification in the case that the user does something again.

**Comment by malekim** [comment]
This is what for you've got `@remind `and `:reminders`. You can use it to show the modal. Currently in the plugin there is event sent on active, but you can easily implement this with `window.addEventListener`. Just remember to clear it in beforeDestroy with `window.removeEventListener.

**Comment by deidyomega** [comment]
@Kuro-dev You can now do this using refresh callback

    <v-idle @refresh="onrefresh" />

    function onrefresh() { console.log("user did something") }
