### ISSUE TITLE
Is TypeScript supported?

### ISSUE THREAD

**Issue by masus04** [malekim/v-idle#32]
Our vueJs project is using typescript, so I was wondering if v-idle supports it and if so, how I can install it accordingly.

When installing according to readme i receive the following error, pointing to the import statement:
```
TS7016: Could not find a declaration file for module 'v-idle'. '/home/masus/workspace/ethz/ape-web-editor/frontend/ape-vue-app/node_modules/v-idle/build/vidle.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/v-idle` if it exists or add a new declaration (.d.ts) file containing `declare module 'v-idle';`

    10 |
  > 11 | import Vidle from 'v-idle'
       |                   ^^^^^^^^
    12 |
```

**Comment by masus04** [comment]
Duplicate of #22

**Comment by eladcandroid** [comment]
@masus04 
Please check here:
https://github.com/eladcandroid/v-idle-3

**Comment by malekim** [comment]
Typescript definitions added
