### ISSUE TITLE
Is it support in multiple tabs ?

### ISSUE THREAD

**Issue by html-helpers** [malekim/v-idle#34]
Hello, 

How to implement this plugin for multiple tabs scenario ?

**Comment by deidyomega** [comment]
@malekim would you have any interest in me doing this using local storage?

    window.localStorage.setItem("last_active", new Date());

    window.addEventListener('storage', (event) => {
       if (event.storageArea != localStorage) return;
       if (event.key === 'last_active') {
         // call refresh()
       }
      });
    
We do this at my company right now to handle idle across browser tabs, which is required as right now if you have 2 tabs open on the offical repo, and you go idle on the second tab, your first tab also gets logged out, even though you were still active.

**Comment by malekim** [comment]
@html-helpers
Added support for multitab scenario through `syncKey`. Please have a look into readme.
