### ISSUE TITLE
syncKey missing on the build

### ISSUE THREAD

**Issue by SergioPujol** [malekim/v-idle#53]
Hi! I was implementing the plugin into my app, I was very interested on keySync property.

I have been trying to implement it, using version 1.0.2. I feel that the build has not been updated with last updates. I decided to check the node_modules/v-idle/build/index.d.ts and looks like the property is not even there.

I was just using the example of the Readme with syncKey, but I was not able to make it work. Even Vue Devtool Extension does not recognize syncKey as a prop and is assigned to attrs.

**Comment by malekim** [comment]
@SergioPujol you're right. I pushed a new version with the latest build.
